name: Deploy API to VM
on:
  push:
    paths:
      - 'apps/api/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'apps/api/package-lock.json'

      - name: Build
        working-directory: apps/api
        run: |
          npm ci
          npm run build || true   # keep if you have a build step

      - name: Rsync to VM
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -az --delete --exclude=node_modules
          path: apps/api/
          remote_path: /srv/apps/api/
          remote_host: ${{ secrets.VM_HOST }}
          remote_user: deploy
          remote_key: ${{ secrets.VM_SSH_KEY }}

      - name: Install prod deps & restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: deploy
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /srv/apps/api
            npm ci --omit=dev
            sudo systemctl restart plaidypus-api
