name: Deploy API to VM
on:
  push:
    paths:
      - 'apps/api/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'package.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm (let it read version from package.json -> "packageManager")
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false   # don't auto-install here

      # Node + pnpm cache
      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Preflight
        run: |
          node -v
          pnpm -v
          which pnpm

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile

      - name: Build API
        run: pnpm --filter ./apps/api run build || true

      # Note: see pnpm deploy notes below if you hit a workspace setting error
      - name: Create deploy bundle
        run: pnpm deploy --filter ./apps/api out/api

      - name: Rsync to VM
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -az --delete
          path: out/api/
          remote_path: /srv/apps/api/
          remote_host: ${{ secrets.VM_HOST }}
          remote_user: deploy
          remote_key: ${{ secrets.VM_SSH_KEY }}

      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: deploy
          key: ${{ secrets.VM_SSH_KEY }}
          script: sudo systemctl restart plaidypus-api
