name: Deploy Auth to VM
on:
  push:
    paths:
      - 'apps/auth/**'
      - 'apps/shared/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'package.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install pnpm per docs; version comes from package.json "packageManager"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node 22 (enable pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Preflight
        run: |
          node -v
          pnpm -v
          which pnpm

      # Install workspace deps (cached)
      - name: Install deps
        run: pnpm install --frozen-lockfile

      # 🔑 Build Auth *and its dependencies* (e.g., apps/shared) in topo order
      - name: Build shared
        run: pnpm --filter @apps/shared build

      - name: Build Auth
        run: pnpm --filter @apps/auth build

      # Produce a pruned, prod-ready bundle (avoid inject-workspace-packages requirement)
      - name: Create deploy bundle
        run: pnpm deploy --prod --legacy --filter "{apps/auth}" out/auth

      - name: Rsync to VM
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -az --delete
          path: out/auth/
          remote_path: /srv/apps/auth/
          remote_host: ${{ secrets.VM_HOST }}
          remote_user: deploy
          remote_key: ${{ secrets.VM_SSH_KEY }}

      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: deploy
          key: ${{ secrets.VM_SSH_KEY }}
          script: sudo systemctl restart plaidypus-auth
