name: Deploy API to VM
on:
  push:
    paths:
      - 'apps/api/**'
      - 'pnpm-lock.yaml'
      - 'package.json'
      - 'pnpm-workspace.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      # This puts pnpm on PATH
      - name: Setup pnpm@10
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      # Redundant but harmless: ensures Corepack activation too
      - name: Activate pnpm via Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10 --activate

      # Prove pnpm is available before using it
      - name: Preflight (print versions)
        run: |
          which pnpm || echo "pnpm NOT on PATH"
          node -v
          pnpm -v

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile

      - name: Build API
        run: pnpm --filter ./apps/api run build || true

      - name: Create deploy bundle
        run: pnpm deploy --filter ./apps/api out/api

      - name: Rsync to VM
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -az --delete
          path: out/api/
          remote_path: /srv/apps/api/
          remote_host: ${{ secrets.VM_HOST }}
          remote_user: deploy
          remote_key: ${{ secrets.VM_SSH_KEY }}

      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: deploy
          key: ${{ secrets.VM_SSH_KEY }}
          script: sudo systemctl restart plaidypus-api
