name: Deploy API to VM
on:
  push:
    paths:
      - 'apps/api/**'
      - 'apps/shared/**'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'package.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install pnpm per docs; version comes from package.json "packageManager"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node 22 (enable pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Preflight
        run: |
          node -v
          pnpm -v
          which pnpm

      # Install workspace deps (cached)
      - name: Install deps
        run: pnpm install --frozen-lockfile

      # 🔑 Build API *and its dependencies* (e.g., apps/shared) in topo order
      - name: Build API & dependencies
        run: |
          cd apps/api
          pnpm exec tsc -b

      # Produce a pruned, prod-ready bundle (avoid inject-workspace-packages requirement)
      - name: Create deploy bundle
        run: pnpm deploy --prod --legacy --filter "{apps/api}" out/api

      - name: Rsync to VM
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -az --delete
          path: out/api/
          remote_path: /srv/apps/api/
          remote_host: ${{ secrets.VM_HOST }}
          remote_user: deploy
          remote_key: ${{ secrets.VM_SSH_KEY }}

      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: deploy
          key: ${{ secrets.VM_SSH_KEY }}
          script: sudo systemctl restart plaidypus-api
